# Setup
title:               iOS gaeng
tagline:             'for UI / UX'
description:         '디자인과 iOS 개발을 공부하는 사람.'
url:                 https://g4eng.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              g4eng
  url:               https://gitbhu.com/g4eng
  email:             gaeng2@kakao.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
